<template>
    <v-container fluid>
        <SensorList :sensors="sensors" />
    </v-container>
</template>

<script>
import SensorList from '@/components/SensorList';
import uniqueId from 'lodash.uniqueid';
let flex = 3;
export default {
    name: 'Home',
    components: {
        SensorList,
    },
    methods: {},
    data() {
        return {
            sensors: [
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Living Room',
                    lastUpdated: '17:30',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Living Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Living Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Living Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Gaming Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Gaming Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: true,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Gaming Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Kitchen',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Kitchen',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: true,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Kitchen',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Kitchen',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Bedroom',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Bedroom',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Motion',
                    location: 'Bedroom',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Motion',
                    location: 'Bedroom',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: true,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Motion',
                    location: 'Bedroom',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Animal Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Animal Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Mag Switch',
                    location: 'Animal Room',
                    lastUpdated: '17:31',
                    online: true,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Vibration Sensor',
                    location: 'Animal Room',
                    lastUpdated: '17:32',
                    online: false,
                    triggered: false,
                    flex: flex,
                },
                {
                    id: uniqueId(),
                    type: 'Vibration Sensor',
                    location: 'Animal Room',
                    lastUpdated: '17:33',
                    online: true,
                    triggered: true,
                    flex: flex,
                },
            ],
        };
    },
};
</script>

<style></style>
